### ISSUE TITLE
XCTest test suite should ignore the main function of the executable under test

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#138]
Currently, linking the test suite for an executable fails with a duplicate symbol error.

Instead, the XCTest plugin should link the test executable in such a way that the other functions and classes of the 'main' source file are visible to tests, but the main function is not.

For example, it is possible to use `ld -r -unexported_symbol _main` to produce an object file without  the main symbol, then link against a main function provided by the test driver.

**Comment by lacasseio** [comment]
A step toward ignoring `_main` symbols would be to avoid generating the implicit one. When a single file is passed to swiftc, an implicit `_main` symbol is created as the source file is thought to be a script file. To prevent this, libraries and xctest bundles should be built with `-parse-as-library` flag.

**Comment by eljobe** [comment]
Was this issue solved with #159, or do we still need to do something to make the XCTest suite ignore the main symbol in the executable under test?

**Comment by lacasseio** [comment]
This issue will most likely be current for XCTest on Linux.

**Comment by big-guy** [comment]
Are there any strong objections to just having a rule that we never link to a `main.o` from the component-under-test?  I think otherwise, we have to either know which object file has a `_main` and filter it or filter all object files before linking to the executable.

This doesn't appear to be something that's done much in the wild based on [this bug report](https://bugs.swift.org/browse/SR-1503).  I think it would be simple to document and provide a good example.

I think the documentation would be something like:
1. To test Swift executables with Gradle, define your `main` function in a file named `main.swift`.
2. Avoid putting code that you would like to test in `main.swift`.
3. If you would like to test your `main` function, <provide example for doing this>.
4. If you put your `main` function in any other file, Gradle will fail to link your test executable.

**Comment by big-guy** [comment]
I found this as well: https://developer.apple.com/swift/blog/?id=7

It seems there are some conventions around `main.swift` being a special file already.

**Comment by lacasseio** [comment]
Thanks @big-guy for gathering all the information regarding the complexity of this issue. I still see some value in trying out what @adammurdoch proposed or finding a way to reexport the executable `_main` symbol under another name.

**Comment by big-guy** [comment]
I've looked a little more and I suppose the filtering problem isn't as hard as I imagined.  We only need to filter `main.o` when there are more than one source file or whatever the object file is when there is a single file.

I think there's an argument to be made to keep things a little simpler and adopt a pattern similar to what I see in many Swift projects.

1. If you have a single source file executable, it's not testable.
1. If you want to test it, move the bulk of the code into another module and add a single `main.swift` entry point to the original module.

I think we can improve the second part by just ignoring `main.o` and saying the way we think Swift projects should be tested is...
1. If you have a single source file executable, it's not testable.
1. If you want to test it, split it into `stuff-i-want-to-test.swift` and `main.swift`.  This skips the business about creating another module.

But I'll see how gross the rename _main is and submit a PR.

**Comment by big-guy** [comment]
@lacasseio could you take a look at https://github.com/gradle/gradle/pull/3410?

**Comment by adammurdoch** [comment]
We don't necessarily need to rename the symbol, we can unexport it instead. We shouldn't use source file filtering.

**Comment by adammurdoch** [comment]
Something to keep in mind is that we're working on testing for native here. XCTest just happens to be the first one we're tackling but they _all_ have this problem. We should solve this problem well for XCTest and reuse this solution for all other testing frameworks as a cross cutting capability.

**Comment by lacasseio** [comment]
How Sterling solve this actually unexport (hide) the `_main` symbol. His solution should be reusable with every native testing framework. Windows isn't targetted by the PR but that is fine for now.

**Comment by big-guy** [comment]
@adammurdoch Yep, I was saying "relocate" but I really just meant hide or unexport. That's what the PR ended up doing.

We now have a `UnexportMainSymbol` task that unexports the main symbol for macOS and Linux.  There are two assumptions: if you have a single object file, that must contain the main symbol or if there are multiple object files, the one that's named "main.o" is the object file with the main symbol.

**Comment by adammurdoch** [comment]
The second assumption means we're back where we started, making assumptions about file names. We should start by unexporting the symbol from _all_ of the object files, and make this incremental and faster later.

**Comment by big-guy** [comment]
For Swift, that is the case.  `main.o` must have the main symbol. 

If we're going to post-process all of the object files any way, I think it would be better to not try to re-use the object files from the production compilation step and recompile those sources for testing.  That's going to fit better with what people try to do with C/C++ (with special flags used only for testing).
